name: Run MyAuto Bot

on:
  schedule:
    - cron: '*/5 * * * *' # اجرای خودکار هر ۵ دقیقه یک‌بار
  workflow_dispatch: # امکان اجرای دستی ربات

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install requests

      - name: Run Script
        run: python bot.py
